### ISSUE TITLE
npz issue when loading phys_anim/data/motions/h1_extended_hands_punch.npy

### ISSUE THREAD

**Issue by Axian12138** [NVlabs/ProtoMotions#11]
hi, thanks for your great work!
but when i try to load phys_anim/data/motions/h1_extended_hands_punch.npy by setting 'motion_file=phys_anim/data/motions/h1_extended_hands_punch.npy' in cmd, i meet 

AttributeError: 'NpzFile' object has no attribute 'item'

seems that phys_anim/data/motions/h1_extended_hands_punch.npy is actually a npz file, if there is something wrong?

**Comment by tesslerc** [comment]
I re-downloaded `h1_extended_hands_punch.npy` from this repo and I can't reproduce this issue.
It seems fine on my end.

From the protomotions folder, I'm running `python phys_anim/scripts/play_motion.py ../Downloads/h1_extended_hands_punch.npy isaacgym h1_extended_hands`
