### ISSUE TITLE
can not find task in config

### ISSUE THREAD

**Issue by Evan-wyl** [NVlabs/ProtoMotions#12]
![Screenshot from 2024-10-16 17-55-03](https://github.com/user-attachments/assets/4f3ee4ab-1ae4-4a2a-8513-346352665a10)

**Comment by tesslerc** [comment]
IsaacSim is not supported yet. Current code is a guide but it doesn't run yet, see readme.
There will be an update in 2-3 weeks adding proper IsaacSim support.

**Comment by tesslerc** [comment]
Please try again now. IsaacSim is now supported.
