### ISSUE TITLE
How to specify the humanoid type when using SMPL+H?

### ISSUE THREAD

**Issue by RunpeiDong** [NVlabs/ProtoMotions#13]
Dear authors,

Thank you for your wonderful work. I have downloaded the AMASS dataset in SMPL+H format. When I am processing the data using the script `data/scripts/convert_amass_to_isaac.py`, it  tells me that I have to download the SMPLH pkl files like SMPLX_NEUTRAL.pkl. Can I ask where I can download the SMPLH files? By the way, is it okay if I specify the humanoid type to `smpl` instead of `smplh`? Since SMPLH uses the same body model as SMPL except for the hands?

**Comment by tesslerc** [comment]
SMPL-H files should be here: https://mano.is.tue.mpg.de/
We support the SMPL and SMPL-X humanoid.
Regarding SMPL-H you are correct, you can use the SMPL-H files and set humanoid type in our code to smpl.
