### ISSUE TITLE
"Could you please upload the SMPL v1.1.0 and SMPL-X v1.1 datasets to a repository? I can't find the corresponding files online. Thanks a lot."

### ISSUE THREAD

**Issue by xiongy24** [NVlabs/ProtoMotions#18]

**Comment by tesslerc** [comment]
Sorry, SMPL and SMPL-X have their own license. We can not host it on our repo.
You should be able to download the SMPL-X parameters from https://smpl-x.is.tue.mpg.de/download.php and SMPL from https://smpl.is.tue.mpg.de/
