### ISSUE TITLE
h1 straight knee and bent knee

### ISSUE THREAD

**Issue by lvhao54** [NVlabs/ProtoMotions#21]
Hello! It has been found that the h1 motion converted by convert_h1_to_isaac.py is with straight knees, while the h1_extended_hands_punch.npy provided by you is with bent knees. Here, I would like to ask what method you used for the conversion?

**Comment by tesslerc** [comment]
The punching motion was a demo provided by https://github.com/LeCAR-Lab/human2humanoid and adapted to our structure.

I'm not sure how they retargeted that specific motion and whether there's any pose optimizations for better robot stability.

**Comment by lvhao54** [comment]
Thanks!
