### ISSUE TITLE
Segmentation fault (core dumped) when collecting data and training in progress

### ISSUE THREAD

**Issue by bowieshi** [NVlabs/ProtoMotions#32]
Hi. I want through the fabric problem by disabling the GPU P2P setting and successfully began multi-GPU training. But I met **Segmentation fault (core dumped)** when collecting data and training in progress. I use GPU 0, 1, 2, 3 to train the model. When the Segmentation fault happens. I stopped training. It seems the training in GPU 0 is stopped by the other three are still running. The GPU RAM usage is still not full. Do you have any advice on this error? Thank you.
I am running with this command:
```
NCCL_P2P_DISABLE=1 CUDA_VISIBLE_DEVICES=0,1,2,3 python phys_anim/train_agent.py \
    +exp=full_body_tracker \
    +robot=smplx \
    +backbone=isaacgym \
    motion_file=AMASS-X/motion_file.pt \
    force_flat_terrain=True \
    algo.config.batch_size=8192 \
    num_envs=2048 \
    +opt=wdb
```
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100 80GB PCIe          Off | 00000000:4F:00.0 Off |                    0 |
| N/A   24C    P0              52W / 300W |     28MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100 80GB PCIe          Off | 00000000:52:00.0 Off |                    0 |
| N/A   28C    P0              75W / 300W |  49348MiB / 81920MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A100 80GB PCIe          Off | 00000000:56:00.0 Off |                    0 |
| N/A   27C    P0              73W / 300W |  48858MiB / 81920MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A100 80GB PCIe          Off | 00000000:57:00.0 Off |                    0 |
| N/A   27C    P0              73W / 300W |  48748MiB / 81920MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
```
<img width="818" alt="image" src="https://github.com/user-attachments/assets/35974980-91b9-49d8-be5f-0d4517330a4b">

**Comment by bowieshi** [comment]
I change the number of environments to 1024. It seems the training can go well. Can I ask about the memory usage of the training? I found it is hard to train in 4096 environments in my A100 80GB GPU even with force_flat_terrain set to be True

**Comment by bowieshi** [comment]
@tesslerc Thank you for your reply! I can train the full_body_tracker with 1024 environments well in my machine. I am currently using fabric to train with 4 A100. According to your reply, you mean you train the full_body_tracker with only one 80GB GPU is enough? Can I also inquire how many epochs you used to train a good full_body_tracker policy. Thank you!

**Comment by tesslerc** [comment]
I meant that I was able to run 4096 envs on each GPU.
For the paper, we trained with 16 GPUs.

I can share that if you train without terrains and objects, the training is much easier and faster.
I believe a week on a single GPU, or 2-3 days on 4+.

**Comment by tesslerc** [comment]
Closing this issue as it is inactive for 3 weeks.
