### ISSUE TITLE
can't find pkl file but only npz files in smplh 

### ISSUE THREAD

**Issue by dbdxnuliba** [NVlabs/ProtoMotions#36]
~/rl/ProtoMotions$ python data/scripts/convert_amass_to_isaac.py /home/rob/rl/ProtoMotions/data/AMASS_Complete/ --humanoid-type=smplh

![image](https://github.com/user-attachments/assets/56490a11-18f1-4843-9ec4-106be49c499e)

**but I can't find pkl file but only npz files in smplh**
https://mano.is.tue.mpg.de/download.php
![image](https://github.com/user-attachments/assets/ddfc9dfa-b89f-43a1-8a0c-92762a962d1f)
![image](https://github.com/user-attachments/assets/f08e56e6-c2db-4111-b6b5-cd1c1a30d565)

**Comment by tesslerc** [comment]
I downloaded the SMPL-X files from https://smpl-x.is.tue.mpg.de/ and use the flag `--humanoid-type=smplx`

**Comment by dbdxnuliba** [comment]
thanks ,I see
