### ISSUE TITLE
Example Amp Training Error

### ISSUE THREAD

**Issue by Steven9Smith** [NVlabs/ProtoMotions#43]
When I run
../IsaacLab/isaaclab.sh -p phys_anim/train_agent.py +exp=amp motion_file=data/motions/amp_humanoid_walk.npy +robot=amp +backbone=isaaclab headless=true

I get the error output:
anaconda/envs/isaacsim2/lib/python3.10/site-packages/torch/functional.py:513: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3609.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Error executing job with overrides: ['+exp=amp', 'motion_file=data/motions/amp_humanoid_walk.npy', '+robot=amp', '+backbone=isaaclab', 'headless=true', 'env=humanoid']
[rank0]: Traceback (most recent call last):
[rank0]:   File "anaconda/envs/isaacsim2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
[rank0]:     return _target_(*args, **kwargs)
[rank0]:   File "Github/Nvidia/ProtoMotions/phys_anim/envs/humanoid/isaaclab.py", line 56, in __init__
[rank0]:     super().__init__(config, device, simulation_app)
[rank0]:   File "Github/Nvidia/ProtoMotions/phys_anim/envs/humanoid/common.py", line 79, in __init__
[rank0]:     super().__init__(config, device, *args, **kwargs)
[rank0]:   File "Github/Nvidia/ProtoMotions/phys_anim/envs/base_interface/isaaclab.py", line 99, in __init__
[rank0]:     raise ValueError(
[rank0]: ValueError: Unsupported robot type: amp_humanoid_3d

[rank0]: The above exception was the direct cause of the following exception:

[rank0]: Traceback (most recent call last):
[rank0]:   File "Github/Nvidia/ProtoMotions/phys_anim/train_agent.py", line 151, in <module>
[rank0]:     main()
[rank0]:   File "anaconda/envs/isaacsim2/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
[rank0]:     _run_hydra(
[rank0]:   File "anaconda/envs/isaacsim2/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
[rank0]:     _run_app(
[rank0]:   File "anaconda/envs/isaacsim2/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
[rank0]:     run_and_report(
[rank0]:   File "anaconda/envs/isaacsim2/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
[rank0]:     raise ex
[rank0]:   File "anaconda/envs/isaacsim2/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
[rank0]:     return func()
[rank0]:   File "anaconda/envs/isaacsim2/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
[rank0]:     lambda: hydra.run(
[rank0]:   File "anaconda/envs/isaacsim2/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
[rank0]:     _ = ret.return_value
[rank0]:   File "anaconda/envs/isaacsim2/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
[rank0]:     raise self._return_value
[rank0]:   File "anaconda/envs/isaacsim2/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
[rank0]:     ret.return_value = task_function(task_cfg)
[rank0]:   File "Github/Nvidia/ProtoMotions/phys_anim/train_agent.py", line 115, in main
[rank0]:     env = instantiate(
[rank0]:   File "anaconda/envs/isaacsim2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 227, in instantiate
[rank0]:     return instantiate_node(
[rank0]:   File "anaconda/envs/isaacsim2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 348, in instantiate_node
[rank0]:     return _call_target(_target_, partial, args, kwargs, full_key)
[rank0]:   File "anaconda/envs/isaacsim2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 98, in _call_target
[rank0]:     raise InstantiationException(msg) from e
[rank0]: hydra.errors.InstantiationException: Error in call to target 'phys_anim.envs.humanoid.isaaclab.Humanoid':
[rank0]: ValueError('Unsupported robot type: amp_humanoid_3d')
[rank0]: full_key: env
[rank0]: ()

[rank0]: kwargs = {'config': {'experiment_name': 'amp', 'num_envs': 4096, 'headless': True, 'backbone': 'isaaclab', 'max_episode_length': 300, 'robot': {'dof_obs_size': 72, 'number_of_actions': 36, 'self_obs_size': 223, 'self_obs_max_coords_size': 223, 'num_bodies': 15, 'contact_bodies': ['pelvis', 'torso', 'head', 'right_upper_arm', 'right_lower_arm', 'right_hand', 'left_upper_arm', 'left_lower_arm', 'left_hand', 'right_thigh', 'right_shin', 'right_foot', 'left_thigh', 'left_shin', 'left_foot'], 'isaacgym_body_names': ['pelvis', 'torso', 'head', 'right_upper_arm', 'right_lower_arm', 'right_hand', 'left_upper_arm', 'left_lower_arm', 'left_hand', 'right_thigh', 'right_shin', 'right_foot', 'left_thigh', 'left_shin', 'left_foot'], 'isaacgym_dof_names': ['abdomen_x', 'abdomen_y', 'abdomen_z', 'neck_x', 'neck_y', 'neck_z', 'right_shoulder_x', 'right_shoulder_y', 'right_shoulder_z', 'right_elbow_x', 'right_elbow_y', 'right_elbow_z', 'left_shoulder_x', 'left_shoulder_y', 'left_shoulder_z', 'left_elbow_x', 'left_elbow_y', 'left_elbow_z', 'right_hip_x', 'right_hip_y', 'right_hip_z', 'right_knee_x', 'right_knee_y', 'right_knee_z', 'right_ankle_x', 'right_ankle_y', 'right_ankle_z', 'left_hip_x', 'left_hip_y', 'left_hip_z', 'left_knee_x', 'left_knee_y', 'left_knee_z', 'left_ankle_x', 'left_ankle_y', 'left_ankle_z'], 'isaacgym_dof_body_ids': [1, 2, 3, 4, 6, 7, 9, 10, 11, 12, 13, 14], 'key_bodies': ['right_hand', 'left_hand', 'right_foot', 'left_foot'], 'non_termination_contact_bodies': ['right_foot', 'left_foot'], 'foot_name': None, 'init_state': None, 'contact_pairs_multiplier': 16, 'num_key_bodies': 4, 'mimic_small_marker_bodies': None, 'control': {'control_type': 'isaac_pd', 'stiffness': None, 'damping': None, 'action_scale': 1.0, 'isaac_pd_scale': False, 'clamp_actions': 1.0}, 'asset': {'collapse_fixed_joints': None, 'replace_cylinder_with_capsule': None, 'flip_visual_attachments': None, 'armature': None, 'thickness': None, 'max_angular_velocity': None, 'max_linear_velocity': None, 'density': None, 'angular_damping': None, 'linear_damping': None, 'disable_gravity': None, 'fix_base_link': None, 'default_dof_drive_mode': 1, 'robot_type': 'amp_humanoid_3d', 'asset_file_name': 'usd/amp_humanoid_3d.usda', 'asset_root': 'phys_anim/data/assets', 'self_collisions': True, 'filter_ints': None}, 'right_foot_name': 'right_foot', 'left_foot_name': 'left_foot'}, 'humanoid_obs': {'use_max_coords_obs': True, 'obs_size': 223, 'local_root_obs': True, 'root_height_obs': True, 'observe_contacts': False}, 'amp_obs': {'disable_discriminator': False, 'discriminator_obs_historical_steps': 10, 'discriminator_obs_size_per_step': 133}, 'termination_height': 0.15, 'head_termination_height': 0.3, 'shield_termination_height': 0.32, 'enable_height_termination': True, 'motion_lib': {'_target_': 'phys_anim.utils.motion_lib.MotionLib', 'motion_file': 'data/motions/amp_humanoid_walk.npy', 'ref_height_adjust': 0.0, 'fix_motion_heights': True}, 'motion_index_offset': None, 'fixed_motion_id': None, 'hybrid_init_prob': 0.0, 'state_init': 'Random', 'ref_respawn_offset': 0.25, 'simulator': {'plane': {'static_friction': 1.0, 'dynamic_friction': 1.0, 'restitution': 0.0}, 'sim': {'fps': 120, 'control_freq_inv': 4, 'substeps': 1, 'physx': {'num_threads': 4, 'solver_type': 1, 'num_position_iterations': 4, 'num_velocity_iterations': 0, 'contact_offset': 0.02, 'rest_offset': 0.0, 'bounce_threshold_velocity': 0.2, 'max_depenetration_velocity': 10.0, 'default_buffer_size_multiplier': 10.0, 'gpu_found_lost_pairs_capacity': 2097152, 'gpu_max_rigid_contact_count': 8388608, 'gpu_found_lost_aggregate_pairs_capacity': 33554432}, 'flex': {'num_inner_iterations': 10, 'warm_start': 0.25}}}, 'terrain': {'_target_': 'phys_anim.envs.env_utils.terrains.flat_terrain.FlatTerrain', 'config': {'terrain_composition': 'curriculum', 'map_length': 20.0, 'map_width': 20.0, 'border_size': 40.0, 'num_levels': 10, 'num_terrains': 1, 'terrain_proportions': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0], 'slope_threshold': 0.9, 'num_samples_per_axis': 16, 'sample_width': 1, 'terrain_obs_num_samples': 256, 'horizontal_scale': 0.1, 'vertical_scale': 0.005, 'spacing_between_scenes': 5, 'minimal_humanoid_spacing': 1, 'terrain_path': None, 'load_terrain': False, 'save_terrain': False}}, 'force_flat_terrain': False, 'scene_lib': None, 'point_cloud_obs': {'enabled': False, 'contacts_relative_to_object_root': False, 'num_pointcloud_samples': 256, 'use_object_identity': False, 'num_point_features': 768, 'num_identity_features': 0, 'num_features_per_object': 843}, 'object_ref_respawn_offset': 0.01, 'visualize_markers': True, 'sync_motion': False, 'output_motion': False, 'camera': None, 'export_video': False, 'export_motion': False, 'record_viewer': False, 'viewer_record_dir': 'output/recordings/viewer'}, 'device': device(type='cuda', index=0), 'simulation_app': <omni.isaac.kit.simulation_app.SimulationApp object at 0x7f2e568eb6d0>}

**Comment by tesslerc** [comment]
AMP humanoid is not properly supported in IsaacLab.
In IsaacLab we currently fully support the SMPL and SMPL-X humanoids.

**Comment by Steven9Smith** [comment]
I see, took a bit to get isaacgym setup but I can confirm that is was training after setup was complete :)
